### PR TITLE
pass initial state when state is undefined and value defined

### PR DESCRIPTION
**Pull request by timche**

### CODE REVIEW

**Comment by timche** [comment]
@danawoodman does this look good?

**Comment by danawoodman** [comment]
@timche yeah the test looks exactly like what I would expect! Nice work!

**Comment by timche** [comment]
Released: https://github.com/redux-utilities/reduce-reducers/releases/tag/v0.4.2

**Comment by danawoodman** [comment]
It's late at night so maybe I'm just tired but I don't think this is working correctly. It appears every time the reduced reducer is called the state gets reset:

```js
const a = (state = { a: false }, action) => {
  if (action.type === 'A') {
    return { ...state, a: true }
  }
  return state
}
const b = (state, action) => {
  if (action.type === 'B') {
    return { ...state, b: true }
  }
  return state
}
const initial = { a: false, b: false }
const reducers = reduceReducers(a, b, initial)

// console.log('A:', a(undefined, { type: 'A' }))

let state = reducers(undefined, { type: 'A' })
console.log('STATE:', state)

state = reducers(state, { type: 'B' })
console.log('STATE:', state)
```

First call returns what you would expect:

```js
{ a: true, b: false }
```

But second call returns:

```js
{ a: false, b: true }
```

But, as far as I can tell, it should return:

```js
{ a: true, b: true }
```

Am I missing something or is it indeed not working right?

**Comment by danawoodman** [comment]
See #18 for a fix

**Pull request merged**
